"use client";
import type { VideoItem } from "@/lib/video-client";
import { formatBytes } from "@/lib/format-bytes";
import { VMBadge, type VMBadgeTone } from "@/components/vm-badge";
const STATUS: Record<string, { label: string; tone: VMBadgeTone }> = { validating: { label: "Validating", tone: "info" }, transcribing: { label: "Transcribing", tone: "warn" }, summarizing: { label: "Summarizing", tone: "accent" }, ready: { label: "Ready", tone: "ok" }, failed: { label: "Failed", tone: "err" } };
export function VideoList({ videos, viewMode, onRename, onDescription, onDelete }: { videos: VideoItem[]; viewMode: "grid" | "list"; onRename: (v: VideoItem) => void; onDescription: (v: VideoItem) => void; onDelete: (v: VideoItem) => void }) {
  if (videos.length === 0) return <p className="text-sm text-ink-2" data-testid="video-list-empty">Upload your first video to get started.</p>;
  return <div className={viewMode === "grid" ? "grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4" : "flex flex-col gap-2"} data-testid="video-list">{videos.map((video) => { const status = STATUS[video.status] ?? { label: video.status, tone: "neutral" as VMBadgeTone }; const image = video.thumbnailUrl ? `/api${video.thumbnailUrl}` : "/video-placeholder.svg"; return <article key={video.id} data-testid="video-card" data-video-id={video.id} className={viewMode === "grid" ? "overflow-hidden rounded-lg border border-line bg-surface shadow-[var(--shadow-vm-sm)]" : "flex items-center gap-4 rounded-lg border border-line bg-surface p-3"}><img src={image} alt="" className={viewMode === "grid" ? "aspect-video h-full w-full object-cover" : "h-16 w-28 rounded object-cover"} /><div className="min-w-0 flex-1 p-3"><div className="flex items-start justify-between gap-2"><h3 className="truncate text-sm font-medium text-ink">{video.title}</h3><VMBadge tone={status.tone}>{status.label}</VMBadge></div><p className="truncate text-xs text-ink-2">{video.description || "No description"}</p><p className="text-xs text-ink-2">{Math.round(video.durationSeconds)}s · {formatBytes(video.sizeBytes)} · {new Date(video.uploadedAt).toLocaleDateString()}</p><div className="mt-2 flex gap-2 text-xs"><button type="button" onClick={() => onRename(video)}>Rename</button><button type="button" onClick={() => onDescription(video)}>Edit description</button><button type="button" onClick={() => onDelete(video)}>Delete</button></div></div></article>; })}</div>;
}
